In [2]:
import numpy as np

### TITULOO

In [5]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### TRANSFORMANDO LA LISTA CON UN ARRAY

In [6]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### COMPROBANDO EL TIPO DE OBJETO

In [7]:
type(arreglo)

numpy.ndarray

### CORROBORANDO EL TIPO DE DATOS DEL ARREGLO

In [9]:
arreglo.dtype

dtype('int32')

### DEFINIENDO EL ARRAY DE INT32 A FLOAT32

In [8]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

### TRANFORMANDO LOS DATOS DE INT32 A FLOAT32

In [ ]:
arreglo.astype

### OBTENIENDO EL PROMEDIO DEL ARREGLO

In [9]:
promedio = np.mean(arreglo)
promedio

5.5

### Creando lista de 10 elementos

In [7]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### CREANDO LISTA CON NUMEROS DE 2 EN 2

In [8]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

### GENERAR ARREGLO DE SOLAMENTES UNOS


In [10]:
arreglo_de_unos = np.ones(20)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

###TRANSFORMAR ARREGLO DE UNOS A ENTEROS

In [11]:
arreglo_int_unos= arreglo_de_unos.astype(int)
arreglo_int_unos

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### ARREGLOS DE CEROS

In [12]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

### GENERANDO ARREGLO DE ELEMENTOS RANDOM

In [18]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio


array([0.75363064, 0.42320257, 0.90178961, 0.68884139, 0.17142276,
       0.71299841, 0.24534682, 0.68907236, 0.6478451 , 0.1253611 ])

### GENERANDO ARREGLO DE NUMERO ALEATORIOS DEL 1 AL 5

In [19]:
arreglo_aleatorio2 = np.random.randint(1, 5, 10)
arreglo_aleatorio2

array([3, 1, 3, 2, 2, 2, 2, 2, 1, 2])

### Generando una matriz de 3x3

In [20]:
matriz = np.random.rand(3,3)
matriz

array([[0.25656897, 0.50055006, 0.92955866],
       [0.65484371, 0.60439969, 0.23686367],
       [0.60992064, 0.02485104, 0.10594969]])

### GENERANDO UNA MATRIZ DE 10 INT DEL 1 AL 100

In [29]:
supermatriz = np.random.randint(1, 100(10, 10))
supermatriz

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\svald\AppData\Local\Temp\ipykernel_4628\1578034428.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  supermatriz = np.random.randint(1, 100(10, 10))


TypeError: 'int' object is not callable